ALTER TABLE public.site_images
  ADD COLUMN IF NOT EXISTS title text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS caption text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS page_key text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS section_key text NOT NULL DEFAULT '';